"""Property-based tests for the space-time prism kernel.

We assert algebraic invariants that must hold for any feasible prism,
across the input space generated by `hypothesis`. These complement the
example-based tests in `test_prism.py` and catch regressions that
hand-picked cases would miss.
"""

from __future__ import annotations

import math
from datetime import UTC, datetime, timedelta

from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from app.components.space_time_prism import (
    Prism,
    haversine_m,
    intersect,
    speed_bounds_for,
)
from app.models import Anchor, AnchorPair

_BOUNDS = speed_bounds_for("vessel", vessel_v_max_kts=25.0, vehicle_v_max_kmh=130.0)
_T0 = datetime(2026, 1, 15, 6, tzinfo=UTC)


def _anchor(lat: float, lon: float, dt: float) -> Anchor:
    return Anchor(lat=lat, lon=lon, t=_T0 + timedelta(seconds=dt))


# ------------------------------------------------------------------ helpers


_lat = st.floats(min_value=-60.0, max_value=60.0, allow_nan=False, allow_infinity=False)
_lon = st.floats(min_value=-160.0, max_value=160.0, allow_nan=False, allow_infinity=False)
_d_lat = st.floats(min_value=-1.0, max_value=1.0, allow_nan=False, allow_infinity=False)
_d_lon = st.floats(min_value=-1.0, max_value=1.0, allow_nan=False, allow_infinity=False)
_dt_s = st.integers(min_value=600, max_value=24 * 3600)  # 10 min to 24 h


# ------------------------------------------------------------------ tests


@settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(_lat, _lon, _d_lat, _d_lon, _dt_s)
def test_feasibility_iff_speed_budget_dominates_distance(
    lat: float, lon: float, dlat: float, dlon: float, dt: int
) -> None:
    pair = AnchorPair(a=_anchor(lat, lon, 0), b=_anchor(lat + dlat, lon + dlon, dt))
    p = Prism.compute(pair, _BOUNDS)
    d = haversine_m(lat, lon, lat + dlat, lon + dlon)
    L = _BOUNDS.v_max_mps * dt
    expected_feasible = d <= (L + 1e-3)
    assert p.feasible == expected_feasible


@settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(_lat, _lon, _d_lat, _d_lon, _dt_s)
def test_feasible_ellipse_semi_axes_are_real(
    lat: float, lon: float, dlat: float, dlon: float, dt: int
) -> None:
    pair = AnchorPair(a=_anchor(lat, lon, 0), b=_anchor(lat + dlat, lon + dlon, dt))
    p = Prism.compute(pair, _BOUNDS)
    e = p.base_ellipse
    if p.feasible:
        assert e.semi_major_m >= e.semi_minor_m >= 0
        assert math.isfinite(e.semi_major_m) and math.isfinite(e.semi_minor_m)
    else:
        assert e.semi_minor_m == 0.0


@settings(max_examples=80, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(_lat, _lon, _d_lat, _d_lon, _dt_s)
def test_self_intersection_nonempty_for_feasible_prism(
    lat: float, lon: float, dlat: float, dlon: float, dt: int
) -> None:
    pair = AnchorPair(a=_anchor(lat, lon, 0), b=_anchor(lat + dlat, lon + dlon, dt))
    p = Prism.compute(pair, _BOUNDS)
    if not p.feasible:
        return
    inter = intersect(p, p, n_slices=8)
    if p.base_ellipse.semi_minor_m > 0:
        assert not inter.is_empty


@settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(_lat, _lon, _d_lat, _d_lon)
def test_haversine_symmetric_and_nonnegative(
    lat: float, lon: float, dlat: float, dlon: float
) -> None:
    a = haversine_m(lat, lon, lat + dlat, lon + dlon)
    b = haversine_m(lat + dlat, lon + dlon, lat, lon)
    assert a >= 0
    assert math.isclose(a, b, rel_tol=1e-9, abs_tol=1e-6)


@settings(max_examples=80, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(_lat, _lon, _d_lat, _d_lon, _dt_s)
def test_mobr_contains_inscribed_ellipse_polygon(
    lat: float, lon: float, dlat: float, dlon: float, dt: int
) -> None:
    pair = AnchorPair(a=_anchor(lat, lon, 0), b=_anchor(lat + dlat, lon + dlon, dt))
    p = Prism.compute(pair, _BOUNDS)
    if not p.feasible or p.base_ellipse.semi_minor_m <= 0:
        return
    mbr = p.mobr()
    poly = p.ellipse_polygon()
    # Buffer the MOBR by a small numerical tolerance to absorb projection
    # round-off; the inscribed ellipse polygon must fit inside.
    assert mbr.buffer(1e-6).contains(poly)
